export const en = {
    "ui.lang-switch": "FR",
    "ui.timer": "Time: 0:00",
    "graphics.ultra-low": "Ultra Low",
    "graphics.low": "Low Graphics",
    "graphics.high": "High Graphics",
    "main.title": "Choose Your Path",
    "main.subtitle": "Enter the fractured dream — each path holds a different truth.",
    "mode.tutorial.title": "Tutorial",
    "mode.tutorial.desc": "Awaken slowly — learn to navigate the shifting cube before the real dream begins.",
    "mode.singleplayer.title": "Single Player",
    "mode.singleplayer.desc": "Traverse the dream alone — collect fragments, dodge nightmares, and reach the crystal to awaken.",
    "mode.multiplayer.title": "Multiplayer",
    "mode.multiplayer.desc": "Face other dreamers in a fractured world — alter their reality or shatter them before they reach the light.",
    "mode.editor.title": "Level Editor",
    "mode.editor.desc": "Bend the dream to your will — craft impossible paths and share your nightmare with others.",
    "ui.start-game": "Start Game",
    "win.title": "VICTORY!",
    "win.subtitle": "You have conquered the night realm",
    "win.score": "Final Score:",
    "win.time": "Time Elapsed:",
    "win.restart": "Restart",
    "win.menu": "Main Menu",
    "gameover.title": "GAME OVER",
    "gameover.subtitle": "The darkness has consumed you...",
    "gameover.score": "Score:",
    "gameover.time": "Time Elapsed:",
    "gameover.retry": "Try Again",
    "gameover.menu": "Main Menu",
    "tutorial.complete.title": "Tutorial Complete!",
    "tutorial.complete.subtitle": "You have mastered the basics. The real dream awaits...",
    "tutorial.complete.continue": "Continue",
    "left": "Left",
    "right": "Right",
    "rotate_left_x": "Left rotation X axis",
    "rotate_right_x": "Right rotation X axis",
    "rotate_left_y": "Left rotation Y axis",
    "rotate_right_y": "Right rotation Y axis",
    "rotate_left_z": "Left rotation Z axis",
    "rotate_right_z": "Right rotation Z axis",
    "pov": "Change Camera",
    "jump": "Jump",
    "action_1": "Action 1",
    "action_2": "Action 2",
    "action_3": "Action 3",
    "action_4": "Action 4",
    "action_5": "Action 5",
    "action_6": "Action 6",
    "action_7": "Action 7",
    "action_8": "Action 8",
    "action_9": "Action 9",
    "action_0": "Action 0",
    "action_minus": "Action -",
    "action_plus": "Action +",
    "save": "Save",
    "delete": "Delete",
    "clone": "Clone",
    "tutorial.phase1.title1": "Objective",
    "tutorial.phase1.desc1": "Reach the crystal.",
    "tutorial.phase1.title2": "Movement",
    "tutorial.phase1.desc2": "Move left and right.",
    "tutorial.phase1.title3": "Jump",
    "tutorial.phase1.desc3": "Jump using the spacebar.",
    "tutorial.phase2.title1": "Map",
    "tutorial.phase2.desc1": "The platforms can rotate in 6 different directions along each axis, with 90° left or right for each rotation.",
    "tutorial.phase3.title1": "Health Points & Traps",
    "tutorial.phase3.desc1": "You have 10 HP, and ground traps reduce HP every second. You can see your HP in the top of the screen.",
    "tutorial.phase3.title2": "Vision & Traps",
    "tutorial.phase3.desc2": "There may be ground traps; changing your point of view (POV) improves visibility.",
    "tutorial.phase4.title1": "Rockets",
    "tutorial.phase4.desc1": "Rockets can fall from the sky and deal 5 HP of instant damage upon collision.",
    "pause.subtitle": "Take a moment to catch your breath",
    "pause.title": "Game Paused",
    "keybinds.instructions": "You can change all your keybinds using the wheel at the top right",
};

export const QWERTY = {
    "left": ["a"],
    "right": ["d"],
    "up": ["w"],
    "down": ["s"],
    "rotate_left_x": ["x"],
    "rotate_right_x": ["c"],
    "rotate_left_y": ["y"],
    "rotate_right_y": ["u"],
    "rotate_left_z": ["h"],
    "rotate_right_z": ["j"],
    "pov": ["p"],
    "jump": [" "],
    "action_1": ["1"],
    "action_2": ["2"],
    "action_3": ["3"],
    "action_4": ["4"],
    "action_5": ["5"],
    "action_6": ["6"],
    "action_7": ["7"],
    "action_8": ["8"],
    "action_9": ["9"],
    "action_0": ["0"],
    "action_minus": ["-"],
    "action_plus": ["+"],
    "save": ["Enter"],
    "delete": ["Backspace"],
    "clone": ["f"]
}