export const fr = {
    "ui.lang-switch": "EN",
    "ui.timer": "Temps : 0:00",
    "graphics.ultra-low": "Ultra Faible",
    "graphics.low": "Graphismes Faibles",
    "graphics.high": "Graphismes Élevés",
    "main.title": "Choisissez votre chemin",
    "main.subtitle": "Entrez dans le rêve fracturé — chaque chemin détient une vérité différente.",
    "mode.tutorial.title": "Tutoriel",
    "mode.tutorial.desc": "Éveillez-vous doucement — apprenez à naviguer dans le cube changeant avant que le vrai rêve ne commence.",
    "mode.singleplayer.title": "Solo",
    "mode.singleplayer.desc": "Traversez le rêve seul — collectez des fragments, évitez les cauchemars et atteignez le cristal pour vous réveiller.",
    "mode.multiplayer.title": "Multijoueur",
    "mode.multiplayer.desc": "Affrontez d'autres rêveurs dans un monde fracturé — altérez leur réalité ou brisez-les avant qu'ils n'atteignent la lumière.",
    "mode.editor.title": "Éditeur de niveau",
    "mode.editor.desc": "Pliez le rêve à votre volonté — créez des chemins impossibles et partagez votre cauchemar avec les autres.",
    "ui.start-game": "Démarrer le jeu",
    "win.title": "VICTOIRE !",
    "win.subtitle": "Vous avez conquis le royaume de la nuit",
    "win.score": "Score final :",
    "win.time": "Temps écoulé :",
    "win.restart": "Recommencer",
    "win.menu": "Menu Principal",
    "gameover.title": "FIN DE PARTIE",
    "gameover.subtitle": "Les ténèbres vous ont consumé...",
    "gameover.score": "Score :",
    "gameover.time": "Temps écoulé :",
    "gameover.retry": "Réessayer",
    "gameover.menu": "Menu Principal",
    "tutorial.complete.title": "Tutoriel terminé !",
    "tutorial.complete.subtitle": "Vous avez maîtrisé les bases. Le vrai rêve vous attend...",
    "tutorial.complete.continue": "Continuer",
    "left": "Gauche",
    "right": "Droite",
    "rotate_left_x": "Rotation à gauche sur l'axe X",
    "rotate_right_x": "Rotation à droite sur l'axe X",
    "rotate_left_y": "Rotation à gauche sur l'axe Y",
    "rotate_right_y": "Rotation à droite sur l'axe Y",
    "rotate_left_z": "Rotation à gauche sur l'axe Z",
    "rotate_right_z": "Rotation à droite sur l'axe Z",
    "pov": "Changer de caméra",
    "jump": "Sauter",
    "action_1": "Action 1",
    "action_2": "Action 2",
    "action_3": "Action 3",
    "action_4": "Action 4",
    "action_5": "Action 5",
    "action_6": "Action 6",
    "action_7": "Action 7",
    "action_8": "Action 8",
    "action_9": "Action 9",
    "action_0": "Action 0",
    "action_minus": "Action -",
    "action_plus": "Action +",
    "save": "Sauvegarder",
    "delete": "Supprimer",
<<<<<<< Updated upstream
    "clone": "Cloner"
=======
    "clone": "Cloner",
    "tutorial.phase1.title1": "Objectif",
    "tutorial.phase1.desc1": "Atteignez le cristal.",
    "tutorial.phase1.title2": "Déplacement",
    "tutorial.phase1.desc2": "Déplacez-vous à droite et à gauche.",
    "tutorial.phase1.title3": "Saut",
    "tutorial.phase1.desc3": "Sautez avec la barre d'espace. Double saut pour atteindre des plateformes plus hautes.",
    "tutorial.phase2.title1": "Carte",
    "tutorial.phase2.desc1": "Les plateformes peuvent pivoter dans 6 directions différentes sur chaque axe, avec 90° à gauche ou à droite pour chaque rotation.",
    "tutorial.phase3.title1": "Points de vie & pièges",
    "tutorial.phase3.desc1": "Vous avez 10 PV et les pièges au sol enlèvent des PV chaque seconde. Vous pouvez voir vos PV en haut de l'ecran.",
    "tutorial.phase3.title2": "Vision & pièges",
    "tutorial.phase3.desc2": "Il peut y avoir des pièges au sol, meilleure visibilité en changeant de point de vue (POV).",
    "tutorial.phase4.title1": "Rockets",
    "tutorial.phase4.desc1": "Des roquettes peuvent tomber du ciel et infliger 5 PV de dégâts instantanés en cas de collision.",
    "tutorial.phase4.title2": "Activation",
    "tutorial.phase4.desc2": "Les roquettes ne sont activées que lorsque vous touchez certaines plateformes. Restez vigilant, vous ne verrez pas la différence.",
    "pause.subtitle": "Prenez un moment pour reprendre votre souffle",
    "pause.title": "Jeu en pause",
    "keybinds.instructions": "Vous pouvez modifier toutes vos touches via l'écrou en haut à droite",
    "forward": "Avant",
    "backward": "Arrière",
>>>>>>> Stashed changes
};

export const AZERTY = {
    "left": ["q"],
    "right": ["d"],
    "rotate_left_x": ["x"],
    "rotate_right_x": ["c"],
    "rotate_left_y": ["a"],
    "rotate_right_y": ["e"],
    "rotate_left_z": ["w"],
    "rotate_right_z": ["r"],
    "pov": ["p"],
    "jump": [" "],
    "action_1": ["&"],
    "action_2": ["é"],
    "action_3": ["\""],
    "action_4": ["'"],
    "action_5": ["("],
    "action_6": ["-"],
    "action_7": ["è"],
    "action_8": ["_"],
    "action_9": ["ç"],
    "action_0": ["à"],
    "action_minus": [")"],
    "action_plus": ["="],
    "save": ["Enter"],
    "delete": ["Backspace"],
    "clone": ["f"]
}